version: "2"

services:
  shooter:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - AMQP_PATH=amqp://auriga:auriga@auriga-devbox:5672
      - AMQP_EXCHANGE=topic
      - AMQP_QUEUE_OUTCOMING=outcoming
      - AMQP_KEY_OUTCOMING=outcoming
    extra_hosts:
      - "auriga-devbox:10.200.5.5"
